version: "3.7"

services:
  phpfpm:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    volumes: &appvolumes
      - sockdata:/sock
      - ../.composer:/var/www/.composer:delegated
      - ../.composer:/var/www/html/var/composer_home:delegated
      - ./docker/config/dockergento/nginx/conf/default.conf:/var/www/conf/nginx/default.conf:delegated
    environment:
      PHP_IDE_CONFIG: serverName=localhost
    depends_on:
      - db
      - elasticsearch

  nginx:
    image: nginx:1.13
    ports:
      - 80:8000
    volumes: *appvolumes
    depends_on:
      - phpfpm

  db:
    image: mariadb:10.5.8
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
    volumes:
      - dbdata:/var/lib/mysql

  node:
    image: modestcoders/node-php:node8-php7.1
    ports:
      - 35729:35729
    volumes: *appvolumes
    depends_on:
      - phpfpm

  elasticsearch:
    image: modestcoders/elasticsearch:6.5
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

volumes:
  dbdata:
  sockdata:
  elasticsearch_data:
